sudo: required

language: javadocker

jdk: oraclejdk8

services:
  - docker

script: mvn clean package docker:build

cache:
  directories:
    - $HOME/.m2

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push julglotain/reactive-heartbeat;
    fi