sudo: required

language: java

jdk: oraclejdk8

services:
  - docker

script: mvn clean test docker:build

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push julglotain/reactive-heartbeat;
    fi
